####

$ZLIB_VERSION = "1.2.11"
$OPENSSL_VERSION = "1.1.1"
$BROTLI_VERSION = "1.0.5"
$LIBSSH2_VERSION = "1.8.0"
$CURL_VERSION="7.61.1"

Write-Host -ForegroundColor Cyan "zlib: $ZLIB_VERSION
openssl: $OPENSSL_VERSION
brotli: $BROTLI_VERSION
libssh2: $LIBSSH2_VERSION
curl: $CURL_VERSION"